import Script from "next/script";
import GridPattern from "@/components/magicui/grid-pattern";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import DotPattern from "@/components/magicui/dot-pattern";
import Providers from "./providers";
import Head from "next/head";
const fatimahArabicFont = localFont({
  src: [
    {
      path: "../fonts/FatimahArabicITF-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/FatimahArabicITF-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/FatimahArabicITF-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/FatimahArabicITF-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={fatimahArabicFont.className}>
      <Head>
        <title>أستديو ضاد | نسرع تطوير المنتجات الرقمية باشتراك شهري</title>
      </Head>
      <Script type="text/javascript" id="zaetoon-widget">
        {`window.chatId = 'efea6ce6-3348-497a-8ca2-7fff43ed2e8f';
  window.locale = 'ar';
  window.position = 'bottom-left';
  window.positionX = 30;
  window.positionY = 30;
  window.borderRadius = 3;
  window.helpdeskURL = 'https://dhad.zaetoon.com';
  (function () {
    d = document;
    s = d.createElement('script');
    s.src = 'https://dhad.zaetoon.com/assets/widget/zaetoon-widget.min.js';
    s.async = 1;
    d.getElementsByTagName('head')[0].appendChild(s);
  })();`}
      </Script>

      <Providers>
        <body className="">{children}</body>
      </Providers>
    </html>
  );
}
